# Generated by Django 4.1.3 on 2022-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('avis', models.TextField(blank=True)),
                ('note', models.IntegerField(choices=[(1, 'Nul'), (2, 'Passable'), (3, 'Assez Bien'), (4, 'Bien'), (5, 'Tres Bien')], default=1)),
                ('date', models.DateField()),
                ('rate', models.IntegerField(default=1)),
            ],
        ),
    ]
